# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ContentBlocker' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ContentBlocker

end

target 'OpenAdBlock' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenAdBlock
  pod 'fishhook'

  target 'OpenAdBlockTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenAdBlockUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
